-- Tabla para gestionar las justificaciones de asistencia
CREATE TABLE `justificaciones_asistencia` (
  `id` int NOT NULL AUTO_INCREMENT,
  `asistencia_clase_id` int NOT NULL,
  `tipo_documento` enum('Incapacidad médica','Excusa familiar','Calamidad doméstica','Otro') COLLATE utf8mb4_general_ci NOT NULL,
  `descripcion` text COLLATE utf8mb4_general_ci NOT NULL,
  `nombre_archivo_original` varchar(255) COLLATE utf8mb4_general_ci NOT NULL,
  `nombre_archivo_sistema` varchar(255) COLLATE utf8mb4_general_ci NOT NULL COMMENT 'UUID del archivo en el sistema',
  `ruta_archivo` varchar(500) COLLATE utf8mb4_general_ci NOT NULL,
  `tipo_mime` varchar(100) COLLATE utf8mb4_general_ci NOT NULL,
  `tamanio_bytes` bigint NOT NULL,
  `fecha_subida` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `subido_por_usuario_id` int NOT NULL,
  `observaciones_docente` text COLLATE utf8mb4_general_ci,
  `fecha_revision` timestamp NULL DEFAULT NULL,
  `revisado_por_usuario_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_una_justificacion_por_asistencia` (`asistencia_clase_id`),
  KEY `fk_justificacion_asistencia` (`asistencia_clase_id`),
  KEY `fk_justificacion_subido_por` (`subido_por_usuario_id`),
  KEY `fk_justificacion_revisado_por` (`revisado_por_usuario_id`),
  KEY `idx_fecha_subida` (`fecha_subida`),
  CONSTRAINT `fk_justificacion_asistencia` FOREIGN KEY (`asistencia_clase_id`) REFERENCES `asistencia_clase` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_justificacion_subido_por` FOREIGN KEY (`subido_por_usuario_id`) REFERENCES `usuarios` (`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `fk_justificacion_revisado_por` FOREIGN KEY (`revisado_por_usuario_id`) REFERENCES `usuarios` (`id_usuario`) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;